/**
 * Full mock of PrismaClient covering every model used in AgencyOS.
 * Returns sensible dummy data for every operation.
 */

// ── Dummy seed data ────────────────────────────────────────────────────
export const DUMMY = {
  org: {
    id: "org-001",
    name: "Test Agency",
    slug: "test-agency-001",
    logo: null,
    website: "https://testagency.com",
    timezone: "UTC",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  user: {
    id: "user-001",
    email: "admin@testagency.com",
    name: "Test Admin",
    avatar: null,
    passwordHash: "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/Lewm6W5K1YPQ6aXIO", // 'password123'
    isActive: true,
    lastLoginAt: new Date("2026-03-22"),
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  lead: {
    id: "lead-001",
    organizationId: "org-001",
    name: "John Doe",
    email: "john@prospect.com",
    phone: "+1-555-0100",
    company: "Prospect Corp",
    website: "https://prospect.com",
    status: "NEW",
    source: "REFERRAL",
    score: 75,
    estimatedValue: 12000,
    notes: "Interested in full-service digital marketing",
    assignedToId: "user-001",
    nextFollowUpAt: null,
    wonAt: null,
    lostAt: null,
    lostReason: null,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-15"),
    activities: [],
    client: null,
    tags: [],
  },
  client: {
    id: "client-001",
    organizationId: "org-001",
    leadId: null,
    name: "Alice Smith",
    email: "alice@acmecorp.com",
    phone: "+1-555-0200",
    company: "Acme Corp",
    website: "https://acmecorp.com",
    industry: "E-Commerce",
    logo: null,
    timezone: "UTC",
    isActive: true,
    portalPassword: null,
    contractValue: 5000,
    billingCycle: "MONTHLY",
    startDate: new Date("2026-01-01"),
    endDate: null,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
    onboarding: { status: "IN_PROGRESS" },
    _count: { projects: 3, invoices: 5 },
    projects: [],
    assets: [],
    credentials: [],
    tags: [],
    portalSessions: [],
    approvals: [],
  },
  project: {
    id: "project-001",
    organizationId: "org-001",
    clientId: "client-001",
    name: "Q1 SEO Campaign",
    description: "Full SEO audit and content strategy for Q1",
    status: "ACTIVE",
    startDate: new Date("2026-01-01"),
    endDate: new Date("2026-03-31"),
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
    client: { id: "client-001", name: "Alice Smith", company: "Acme Corp", logo: null },
    _count: { tasks: 12, milestones: 3 },
    tasks: [],
    milestones: [],
    tags: [],
  },
  task: {
    id: "task-001",
    projectId: "project-001",
    parentId: null,
    title: "Keyword Research",
    description: "Research 200 target keywords for Acme Corp",
    status: "IN_PROGRESS",
    priority: "HIGH",
    assigneeId: "user-001",
    creatorId: "user-001",
    dueDate: new Date("2026-03-25"),
    estimatedHrs: 8,
    order: 1,
    isQaRequired: true,
    qaApprovedAt: null,
    completedAt: null,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
    assignee: { id: "user-001", name: "Test Admin", avatar: null },
    creator: { id: "user-001", name: "Test Admin", avatar: null },
    subtasks: [],
    comments: [],
    timeEntries: [],
    attachments: [],
    _count: { subtasks: 0, comments: 2 },
  },
  invoice: {
    id: "invoice-001",
    organizationId: "org-001",
    clientId: "client-001",
    number: "INV-ABC123",
    status: "SENT",
    currency: "USD",
    subtotal: 5000,
    tax: 500,
    total: 5500,
    dueDate: new Date("2026-04-01"),
    paidAt: null,
    notes: "March retainer",
    stripePaymentIntentId: null,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
    client: { name: "Alice Smith", company: "Acme Corp" },
    lineItems: [
      { id: "li-001", invoiceId: "invoice-001", description: "Monthly Retainer", quantity: 1, unitPrice: 5000, total: 5000 },
    ],
    payments: [],
    _count: { lineItems: 1 },
  },
  socialPost: {
    id: "post-001",
    socialAccountId: "sa-001",
    caption: "Excited to share our latest case study! 🚀 #DigitalMarketing",
    mediaUrls: ["https://cdn.example.com/image.jpg"],
    hashtags: ["#DigitalMarketing", "#SEO", "#Growth"],
    status: "SCHEDULED",
    scheduledAt: new Date("2026-03-25T10:00:00Z"),
    publishedAt: null,
    failureReason: null,
    approvalId: null,
    createdAt: new Date("2026-03-20"),
    updatedAt: new Date("2026-03-20"),
    socialAccount: { platform: "INSTAGRAM", accountName: "@acmecorp" },
    approval: null,
    metrics: [],
  },
  emailCampaign: {
    id: "campaign-001",
    organizationId: "org-001",
    listId: "list-001",
    segmentId: null,
    name: "March Newsletter",
    subject: "Your March Digital Marketing Insights",
    previewText: "See what's trending in digital marketing this month",
    htmlBody: "<h1>March Newsletter</h1><p>Hello {{firstName}},</p>",
    textBody: "March Newsletter\n\nHello,",
    status: "DRAFT",
    scheduledAt: null,
    sentAt: null,
    totalSent: 0,
    totalOpened: 0,
    totalClicked: 0,
    totalBounced: 0,
    totalUnsubscribed: 0,
    abVariant: null,
    abTestParentId: null,
    createdAt: new Date("2026-03-20"),
    updatedAt: new Date("2026-03-20"),
    list: { name: "Main List" },
    _count: { sends: 0 },
  },
  seoProject: {
    id: "seo-001",
    organizationId: "org-001",
    clientId: "client-001",
    domain: "acmecorp.com",
    createdAt: new Date("2026-01-01"),
    _count: { keywords: 45, backlinks: 312, audits: 3 },
  },
  adAccount: {
    id: "ad-account-001",
    organizationId: "org-001",
    clientId: "client-001",
    platform: "GOOGLE_ADS",
    accountId: "123-456-7890",
    accountName: "Acme Corp - Google Ads",
    currency: "USD",
    accessToken: "tok_xxx",
    refreshToken: null,
    tokenExpiry: null,
    isActive: true,
    createdAt: new Date("2026-01-01"),
    _count: { campaigns: 5 },
  },
  approval: {
    id: "approval-001",
    clientId: "client-001",
    title: "March Social Media Posts Review",
    description: "Please review and approve the 10 posts scheduled for March",
    type: "social_post",
    fileUrl: "https://cdn.example.com/posts-preview.pdf",
    status: "PENDING",
    feedback: null,
    reviewedAt: null,
    dueDate: new Date("2026-03-24"),
    createdAt: new Date("2026-03-20"),
    client: { name: "Alice Smith", company: "Acme Corp" },
    socialPost: null,
  },
  report: {
    id: "report-001",
    organizationId: "org-001",
    clientId: "client-001",
    templateId: null,
    title: "Monthly Report",
    period: "monthly",
    startDate: new Date("2026-03-01"),
    endDate: new Date("2026-03-31"),
    data: { summary: { sessions: 42800, conversions: 284, spend: 8400, revenue: 35200 } },
    pdfUrl: null,
    sentAt: null,
    createdAt: new Date("2026-03-22"),
  },
  notification: {
    id: "notif-001",
    userId: "user-001",
    type: "TASK_ASSIGNED",
    title: "New task assigned",
    body: "You have been assigned: Keyword Research",
    link: "/tasks/task-001",
    isRead: false,
    createdAt: new Date("2026-03-22"),
  },
};

// ── Mock Prisma ────────────────────────────────────────────────────────
export function createMockPrisma() {
  const make = (data: any) => ({
    findMany: vi.fn().mockResolvedValue(Array.isArray(data) ? data : [data]),
    findUnique: vi.fn().mockResolvedValue(data),
    findFirst: vi.fn().mockResolvedValue(data),
    create: vi.fn().mockImplementation(({ data: d }: any) => Promise.resolve({ ...data, ...d, id: data.id })),
    update: vi.fn().mockImplementation(({ data: d }: any) => Promise.resolve({ ...data, ...d })),
    updateMany: vi.fn().mockResolvedValue({ count: 1 }),
    upsert: vi.fn().mockImplementation(({ create: c }: any) => Promise.resolve({ ...data, ...c })),
    delete: vi.fn().mockResolvedValue(data),
    count: vi.fn().mockResolvedValue(1),
    aggregate: vi.fn().mockResolvedValue({ _sum: { amount: 50000, total: 45000, durationMin: 480, value: 9999 }, _avg: { value: 4.2, roas: 4.2, ctr: 0.035, cpa: 28 } }),
    groupBy: vi.fn().mockResolvedValue([{ status: "ACTIVE", _count: 5 }, { metric: "sessions", _sum: { value: 42000 }, _avg: { value: 4200 } }]),
  });

  return {
    user: make(DUMMY.user),
    organization: make(DUMMY.org),
    organizationUser: {
      ...make({ ...DUMMY.org, role: "ADMIN", user: DUMMY.user }),
      findMany: vi.fn().mockResolvedValue([{ organizationId: "org-001", userId: "user-001", role: "ADMIN", user: DUMMY.user, organization: DUMMY.org }]),
    },
    session: make({ id: "sess-001", userId: "user-001", token: "tok_xxx", expiresAt: new Date("2026-04-01") }),
    lead: { ...make(DUMMY.lead), findMany: vi.fn().mockResolvedValue({ leads: [DUMMY.lead], total: 1, page: 1, limit: 25 }) },
    leadActivity: make({ id: "act-001", leadId: "lead-001", type: "note", title: "Lead created", createdBy: "user-001", createdAt: new Date() }),
    client: make(DUMMY.client),
    onboarding: make({ id: "ob-001", clientId: "client-001", status: "IN_PROGRESS", checklist: [], responses: [], completedAt: null, createdAt: new Date(), updatedAt: new Date() }),
    onboardingItem: make({ id: "item-001", onboardingId: "ob-001", title: "Collect brand assets", isCompleted: false, isRequired: true, order: 1, completedAt: null }),
    questionnaireResponse: make({ id: "qr-001", onboardingId: "ob-001", question: "What is your target audience?", answer: "B2B SMEs", answeredAt: new Date() }),
    clientAsset: make({ id: "asset-001", clientId: "client-001", name: "Logo", type: "logo", url: "https://cdn.example.com/logo.png", mimeType: "image/png", sizeBytes: 24000, uploadedAt: new Date() }),
    clientCredential: make({ id: "cred-001", clientId: "client-001", platform: "google_ads", label: "Main Account", username: "ads@acmecorp.com", createdAt: new Date() }),
    clientPortalSession: make({ id: "cps-001", clientId: "client-001", token: "client_tok_xxx", expiresAt: new Date("2026-03-23") }),
    project: make(DUMMY.project),
    task: { ...make(DUMMY.task), findMany: vi.fn().mockResolvedValue([DUMMY.task]) },
    milestone: make({ id: "ms-001", projectId: "project-001", title: "Phase 1 Complete", dueDate: new Date("2026-02-28"), completedAt: null, createdAt: new Date() }),
    timeEntry: make({ id: "te-001", taskId: "task-001", userId: "user-001", description: "Worked on research", startedAt: new Date(), stoppedAt: null, durationMin: 60, createdAt: new Date() }),
    comment: make({ id: "cmt-001", taskId: "task-001", userId: "user-001", body: "Updated the keyword list", createdAt: new Date(), updatedAt: new Date(), user: DUMMY.user }),
    taskAttachment: make({ id: "att-001", taskId: "task-001", name: "research.xlsx", url: "https://cdn.example.com/research.xlsx", uploadedAt: new Date() }),
    analyticsIntegration: make({ id: "ai-001", clientId: "client-001", platform: "ga4", accountId: "G-XXXXXXXXXX", isActive: true, createdAt: new Date(), updatedAt: new Date() }),
    metricSnapshot: make({ id: "ms-001", integrationId: "ai-001", date: new Date("2026-03-01"), metric: "sessions", value: 4200, dimensions: null, createdAt: new Date() }),
    report: make(DUMMY.report),
    reportTemplate: make({ id: "rt-001", organizationId: "org-001", name: "Default Monthly", config: { sections: ["overview", "seo", "ads"] }, isDefault: true, createdAt: new Date(), updatedAt: new Date() }),
    alert: make({ id: "alert-001", clientId: "client-001", metric: "sessions", condition: "lt", threshold: 1000, severity: "WARNING", isActive: true, triggeredAt: null, resolvedAt: null, createdAt: new Date() }),
    socialAccount: make({ id: "sa-001", organizationId: "org-001", clientId: "client-001", platform: "INSTAGRAM", accountId: "ig_acme", accountName: "@acmecorp", isActive: true, createdAt: new Date() }),
    socialPost: make(DUMMY.socialPost),
    socialPostMetric: make({ id: "spm-001", postId: "post-001", fetchedAt: new Date(), likes: 142, comments: 18, shares: 24, reach: 3200, impressions: 4800, clicks: 87, saves: 31 }),
    emailList: make({ id: "list-001", organizationId: "org-001", name: "Main List", description: "Primary email list", _count: { subscribers: 1240 }, subscribers: [], segments: [], campaigns: [] }),
    emailSubscriber: make({ id: "sub-001", listId: "list-001", email: "subscriber@example.com", firstName: "Jane", lastName: "Doe", tags: [], isActive: true, subscribedAt: new Date(), unsubscribedAt: null }),
    emailSegment: make({ id: "seg-001", listId: "list-001", name: "Opened Last 30 Days", rules: [{ field: "lastOpenedAt", operator: "gte", value: "30d" }], createdAt: new Date() }),
    emailCampaign: make(DUMMY.emailCampaign),
    emailSequence: make({ id: "seq-001", campaignId: "campaign-001", name: "Day 3 Follow-up", delayDays: 3, delayHours: 0, subject: "Did you see this?", htmlBody: "<p>Following up...</p>", order: 1, createdAt: new Date() }),
    emailSend: make({ id: "send-001", campaignId: "campaign-001", subscriberId: "sub-001", sentAt: new Date(), openedAt: null, clickedAt: null, bouncedAt: null, unsubscribedAt: null }),
    seoProject: make(DUMMY.seoProject),
    seoKeyword: make({ id: "kw-001", seoProjectId: "seo-001", keyword: "digital marketing agency", targetUrl: "/services", country: "US", language: "en", createdAt: new Date(), rankings: [{ position: 4, date: new Date(), url: "/services" }] }),
    keywordRanking: make({ id: "kr-001", keywordId: "kw-001", position: 4, url: "/services", searchVolume: 8100, date: new Date("2026-03-22"), createdAt: new Date() }),
    backlink: make({ id: "bl-001", seoProjectId: "seo-001", sourceUrl: "https://blog.example.com/seo-tips", targetUrl: "https://acmecorp.com", anchorText: "digital marketing", doFollow: true, domainRating: 52, firstSeenAt: new Date(), lastSeenAt: new Date(), isLost: false, lostAt: null }),
    seoAudit: make({ id: "audit-001", seoProjectId: "seo-001", score: 87, issues: [{ type: "missing_alt", severity: "low", url: "/about", description: "Image missing alt text" }], pagesScanned: 48, auditedAt: new Date() }),
    adAccount: make(DUMMY.adAccount),
    adCampaign: make({ id: "campaign-ad-001", adAccountId: "ad-account-001", externalId: "ext-001", name: "Brand Awareness Q1", status: "active", objective: "REACH", dailyBudget: 150, totalBudget: 4500, startDate: new Date("2026-01-01"), endDate: new Date("2026-03-31"), createdAt: new Date(), updatedAt: new Date(), adAccount: DUMMY.adAccount, adSets: [], metrics: [], rules: [], _count: { adSets: 3 } }),
    adSet: make({ id: "adset-001", campaignId: "campaign-ad-001", externalId: "adset-ext-001", name: "18-35 Interests", status: "active", dailyBudget: 50, targeting: { age_min: 18, age_max: 35 }, ads: [] }),
    ad: make({ id: "ad-001", adSetId: "adset-001", externalId: "ad-ext-001", name: "Hero Creative v1", status: "active", headline: "Grow Your Business", description: "Digital marketing that delivers results", mediaUrl: "https://cdn.example.com/ad-hero.jpg", destinationUrl: "https://acmecorp.com/contact" }),
    adMetric: make({ id: "am-001", campaignId: "campaign-ad-001", date: new Date("2026-03-22"), impressions: 14200, clicks: 384, spend: 142, conversions: 12, revenue: 1440, reach: 11800, ctr: 0.027, cpc: 0.37, cpm: 10, roas: 10.14, cpa: 11.83, createdAt: new Date() }),
    adRule: make({ id: "rule-001", campaignId: "campaign-ad-001", name: "Pause if CPA > $50", metric: "cpa", condition: "gt", threshold: 50, action: "pause_campaign", adjustment: null, isActive: true, lastRanAt: null, createdAt: new Date() }),
    approval: make(DUMMY.approval),
    invoice: make(DUMMY.invoice),
    invoiceLineItem: make({ id: "li-001", invoiceId: "invoice-001", description: "Monthly Retainer", quantity: 1, unitPrice: 5000, total: 5000 }),
    payment: make({ id: "pay-001", invoiceId: "invoice-001", amount: 5500, method: "stripe", reference: "pi_xxx", paidAt: new Date(), notes: null }),
    subscription: make({ id: "sub-plan-001", clientId: "client-001", planName: "Growth", amount: 5000, billingCycle: "MONTHLY", nextBillingAt: new Date("2026-04-01"), stripeSubId: "sub_xxx", isActive: true, createdAt: new Date() }),
    tag: make({ id: "tag-001", organizationId: "org-001", name: "E-Commerce", color: "#6366f1" }),
    tagOnLead: make({ tagId: "tag-001", leadId: "lead-001" }),
    tagOnClient: make({ tagId: "tag-001", clientId: "client-001" }),
    tagOnProject: make({ tagId: "tag-001", projectId: "project-001" }),
    notification: make(DUMMY.notification),
    auditLog: make({ id: "log-001", userId: "user-001", action: "created", entity: "Lead", entityId: "lead-001", before: null, after: DUMMY.lead, ipAddress: "127.0.0.1", createdAt: new Date() }),
    webhook: make({ id: "wh-001", organizationId: "org-001", url: "https://hooks.example.com/agency-os", events: ["lead.created", "invoice.paid"], secret: "whsec_xxx", isActive: true, createdAt: new Date() }),
    $transaction: vi.fn().mockImplementation((ops: any[]) => Promise.all(ops)),
    $disconnect: vi.fn().mockResolvedValue(undefined),
  };
}
